### ISSUE TITLE
Change asset `path` query param to match using prefix 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#77]
ATM there is only 
```
/dandisets/{parent_lookup_version__dandiset__pk}/versions/{parent_lookup_version__version}/assets/
```
to get listing of all the assets in a dandiset.  If it is desired to download just a single folder (subject), it is needed to first get a full listing (could be large) and then select only the entries matching the desired location. There is also
```
/dandisets/{parent_lookup_version__dandiset__pk}/versions/{parent_lookup_version__version}/assets/paths/
```
to just get paths on the top level of the dandiset.  ATM we do have indeed only 1 level of subdirectories, but it will change e.g. with BIDS (could have `ses-XXX/` subfolder per subject).

I think the easiest way around would be to allow `location=` option (mimicing current new web UI file browsing option name, as in https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000006/0.200714.1807/files?location=%2Fsub-anm369962%2F) to be allowed to both of those API calls to limit for a given location

**Comment by yarikoptic** [comment]
better one thought might be to provision it directly in the URL, e.g.
```
/dandisets/{parent_lookup_version__dandiset__pk}/versions/{parent_lookup_version__version}/assets/location/{location}
```
and
```
/dandisets/{parent_lookup_version__dandiset__pk}/versions/{parent_lookup_version__version}/assets/paths/location/{location}
```

**Comment by yarikoptic** [comment]
additional 1c: I somewhat dislike the choice of `location` term here.  If it is `paths/` in API, a better one would have been `path/`.

**Comment by AlmightyYakob** [comment]
@yarikoptic Currently on the asset listing endpoint (`.../assets/`), there's a `path` query parameter, which if specified, will return the asset that matches that exact path. Example request below:
```
GET https://publish.dandiarchive.org/api/dandisets/000006/versions/0.200714.1807/assets/?path=%2Fsub-anm369962%2Fsub-anm369962_ses-20170309.nwb

{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "version": {
        "dandiset": {
          "identifier": "000006",
          "created": "2020-07-14T18:07:58.698604Z",
          "updated": "2020-07-14T18:07:58.698622Z"
        },
        "version": "0.200714.1807",
        "created": "2020-07-14T18:07:59.179296Z",
        "updated": "2020-07-14T18:07:59.179341Z"
      },
      "uuid": "846617c7-32f2-4dad-aa36-be03ba062e34",
      "path": "/sub-anm369962/sub-anm369962_ses-20170309.nwb",
      "size": 796920,
      "sha256": "8d1e87886816241d34c0ca248fc564d325c3aae1a35d0b22e01900ab1bd1a442",
      "created": "2020-07-14T18:07:59.710618Z",
      "updated": "2020-07-14T18:07:59.710660Z"
    }
  ]
}

```

I think the best path forward would be to allow this to work as a prefix search, instead of an exact match. So specifying `/sub-anm369962/` (instead of the full path from the request above) in the `path` query parameter would return all assets in that "folder" (including the asset response shown above). Would that address your concerns?

**Comment by yarikoptic** [comment]
> @yarikoptic Currently on the asset listing endpoint (`.../assets/`), there's a `path` query parameter, which if specified, will return the asset that matches that exact path.

I am really not sure how I have missed it in swagger -- I did look ( I think).  I need a vacation!

> I think the best path forward would be to allow this to work as a prefix search, instead of an exact match. So specifying /sub-anm369962/ (instead of the full path from the request above) in the path query parameter would return all assets in that "folder" (including the asset response shown above). Would that address your concerns?

**YES**!

**Comment by mgrauer** [comment]
Everyone needs a vacation! 

I'm closing this issue now that it is solved. I want to start maintaining better hygiene in the issue tracker for this repo.

**Comment by yarikoptic** [comment]
@mgrauer yeap, in dire need!  But I think this issue isn't really resolved.  There is `path` but as we discussed with @AlmightyYakob  - it is really for just a specific path, not a prefix, i.e. to e.g. list assets of a specific folder.  I have tried just now and reconfirmed that it is not yet implemented.  I will reopen

**Comment by mgrauer** [comment]
@yarikoptic  Can you provide a specific example of what query you need to run and what results you expect, using an existing dandiset on dandiarchive.org? To make sure we are on the same page.

**Comment by yarikoptic** [comment]
list assets(files) for https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000006/draft/files?_id=5e70d3053da50caa9adaf2d8&_modelType=folder

**Comment by yarikoptic** [comment]
oops -- that was for a draft... here is the one https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000006/0.200714.1807/files?location=%2Fsub-anm369962%2F  so per discussion above it was agreed that having `path` option to react properly to `/sub-anm369962/` to serve as a prefix is a sensible thing to do

**Comment by mgrauer** [comment]
Are you saying that 

`https://publish.dandiarchive.org/api/dandisets/000006/versions/0.200714.1807/assets/?path=%2Fsub-anm369962%2F`

should return the set of assets under that path, but it currently does not?

**Comment by yarikoptic** [comment]
There is no releases for any "real" dandiset ATM. The only one is https://gui.dandiarchive.org/#/dandiset/000027/0.200721.2222 and yes, for that one neither "path" or "location" (to be inline with web ui) is supported ATM
```shell
$> curl https://publish.dandiarchive.org/api/dandisets/000006/versions/0.200714.1807/assets/?path=%2Fsub-RAT123%2F
{"count":0,"next":null,"previous":null,"results":[]}% 
$> curl https://publish.dandiarchive.org/api/dandisets/000006/versions/0.200714.1807/assets/?location=%2Fsub-RAT123%2F
{"count":0,"next":null,"previous":null,"results":[]}%  
```
